# Build settings

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Site settings

title_en: Data Curation Survival Guide
title_fr: Curation de données
author: Portage Curation Expert Group
url: "https://portage-ceg.github.io"
email: #
description: #A simple and awesome blog theme powered by jekyll.
keywords: # [""]


lang: en
languages: ["en", "fr"]
permalink: pretty

collections:
  posts:
    output: true
    permalink: /:path

social:
  github_username:  portage-CEG
